CREATE TABLE IF NOT EXISTS `tbl_declaration_consent` (
  `id`             INT(11)      NOT NULL AUTO_INCREMENT,
  `application_id` INT(11)      NOT NULL COMMENT 'FK tbl_client_application.id',
  `prospect_id`    INT(11)      NOT NULL COMMENT 'FK tbl_client_prospect.id, denormalized for lookups',
  `client_name`    VARCHAR(150) DEFAULT NULL COMMENT 'snapshot at creation',
  `client_email`   VARCHAR(100) DEFAULT NULL,
  `client_phone`   VARCHAR(30)  DEFAULT NULL,
  `category_id`    INT(11)      DEFAULT NULL COMMENT 'snapshot, application category',
  `type_id`        INT(11)      DEFAULT NULL COMMENT 'snapshot, application type',
  `consent_type`   VARCHAR(150) DEFAULT NULL COMMENT 'e.g. Risk Acknowledgement, Medical Issue, free text',
  `title`          VARCHAR(255) DEFAULT NULL COMMENT 'Document Title',
  `content`        LONGTEXT     DEFAULT NULL COMMENT 'Dynamic Content, rich text HTML written/pasted by admin',
  `consultant_name` VARCHAR(150) DEFAULT NULL COMMENT 'staff member who prepared it, informational only — client signs, not the consultant',
  `consent_date`   DATE         DEFAULT NULL,
  `status`         VARCHAR(20)  NOT NULL DEFAULT 'draft' COMMENT 'draft|sent|viewed|signed|declined|cancelled',
  `hide`           TINYINT(1)   NOT NULL DEFAULT 0 COMMENT 'soft-hide/archive, never hard delete',
  `created_by`     INT(11)      DEFAULT NULL COMMENT 'tbl_reg.id / session id of staff who created it',
  `insert_on`      DATETIME     DEFAULT NULL,
  `update_on`      DATETIME     DEFAULT NULL,
  `require_client_signature` TINYINT(1) DEFAULT 1,
  `require_initials`         TINYINT(1) DEFAULT 0 COMMENT 'whether the client must also provide initials, separate from the full signature',
  `show_consent_checkbox`    TINYINT(1) DEFAULT 1 COMMENT '"I have read and understand the above declaration" checkbox on the signing page',
  `sign_token`      VARCHAR(64)  DEFAULT NULL COMMENT 'generated lazily when a signing link is first created',
  `last_sent_at`    DATETIME     DEFAULT NULL COMMENT 'set on every successful send email; guards against duplicate sends from rapid double-clicks',
  `viewed_at`       DATETIME     DEFAULT NULL,
  `viewed_ip`       VARCHAR(45)  DEFAULT NULL,
  `client_signature`      VARCHAR(255) DEFAULT NULL COMMENT 'file path, current (draft or final) client signature image',
  `client_signature_type` VARCHAR(10)  DEFAULT NULL COMMENT 'draw|type|upload',
  `client_typed_name`     VARCHAR(150) DEFAULT NULL COMMENT 'only set when signature_type = type',
  `client_initials`       VARCHAR(255) DEFAULT NULL COMMENT 'file path, image initials (draw/upload)',
  `client_initials_type`  VARCHAR(10)  DEFAULT NULL COMMENT 'draw|type|upload',
  `client_typed_initials` VARCHAR(20)  DEFAULT NULL COMMENT 'only set when initials_type = type',
  `consent_accepted`  TINYINT(1)   NOT NULL DEFAULT 0,
  `client_signed_at`  DATETIME     DEFAULT NULL,
  `client_signed_ip`  VARCHAR(45)  DEFAULT NULL,
  `client_signed_device`  VARCHAR(255) DEFAULT NULL COMMENT 'user agent string, captured at signing',
  `client_signed_browser` VARCHAR(150) DEFAULT NULL COMMENT 'parsed browser name/version, captured at signing',
  `declined_at`     DATETIME     DEFAULT NULL,
  `decline_reason`  VARCHAR(255) DEFAULT NULL,
  `pdf_path`        VARCHAR(255) DEFAULT NULL COMMENT 'file path under public/assets/declaration_pdfs/, generated + locked once signed',
  PRIMARY KEY (`id`),
  KEY `idx_application_id` (`application_id`),
  KEY `idx_prospect_id` (`prospect_id`),
  UNIQUE KEY `uniq_sign_token` (`sign_token`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
