CREATE TABLE IF NOT EXISTS `tbl_agreement_agreement` (
  `id`             INT(11)      NOT NULL AUTO_INCREMENT,
  `application_id` INT(11)      NOT NULL COMMENT 'FK tbl_client_application.id',
  `prospect_id`    INT(11)      NOT NULL COMMENT 'FK tbl_client_prospect.id, denormalized for lookups',
  `client_name`    VARCHAR(150) DEFAULT NULL COMMENT 'snapshot at draft creation',
  `client_email`   VARCHAR(100) DEFAULT NULL,
  `client_phone`   VARCHAR(30)  DEFAULT NULL,
  `category_id`    INT(11)      DEFAULT NULL COMMENT 'snapshot, editable in a later phase',
  `type_id`        INT(11)      DEFAULT NULL COMMENT 'snapshot, editable in a later phase',
  `status`         VARCHAR(20)  NOT NULL DEFAULT 'draft' COMMENT 'draft|sent|viewed|signed|declined|cancelled',
  `hide`           TINYINT(1)   NOT NULL DEFAULT 0 COMMENT 'soft-hide, never hard delete',
  `created_by`     INT(11)      DEFAULT NULL COMMENT 'tbl_reg.id / session id of staff who triggered it',
  `insert_on`      DATETIME     DEFAULT NULL,
  `update_on`      DATETIME     DEFAULT NULL,
  `active_application_id` INT(11) GENERATED ALWAYS AS (IF(`hide` = 0, `application_id`, NULL)) VIRTUAL COMMENT 'NULL when hidden, so hidden rows never block a new draft for the same application',
  `reference_number` VARCHAR(30)   DEFAULT NULL COMMENT 'e.g. SIA-2026-000145, generated lazily from id',
  `agreement_date`   DATE          DEFAULT NULL,
  `consultant_name`  VARCHAR(150)  DEFAULT NULL,
  `rcic_number`      VARCHAR(30)   DEFAULT NULL,
  `currency`         VARCHAR(10)   DEFAULT 'CAD',
  `template_name`    VARCHAR(100)  DEFAULT 'Default Template',
  `service_fee`      DECIMAL(10,2) DEFAULT 0,
  `gst_rate`         DECIMAL(5,2)  DEFAULT 5.00,
  `gst_amount`       DECIMAL(10,2) DEFAULT 0,
  `government_fee`   DECIMAL(10,2) DEFAULT 0,
  `other_fee`        DECIMAL(10,2) DEFAULT 0,
  `total_amount`     DECIMAL(10,2) DEFAULT 0,
  `require_client_signature`     TINYINT(1) DEFAULT 1,
  `require_consultant_signature` TINYINT(1) DEFAULT 1,
  `email_verification`          TINYINT(1) DEFAULT 1,
  `send_reminder`                TINYINT(1) DEFAULT 1,
  `reminder_days`    INT(11) DEFAULT 3,
  `max_reminders`    INT(11) DEFAULT 2,
  `sign_token`         VARCHAR(64)  DEFAULT NULL COMMENT 'generated lazily when a signing link is first created',
  `viewed_at`          DATETIME     DEFAULT NULL,
  `viewed_ip`          VARCHAR(45)  DEFAULT NULL,
  `consultant_signature` VARCHAR(255) DEFAULT NULL COMMENT 'file path under public/assets/agreement_signatures/',
  `client_signature`      VARCHAR(255) DEFAULT NULL COMMENT 'file path, current (draft or final) client signature image',
  `client_signature_type` VARCHAR(10)  DEFAULT NULL COMMENT 'draw|type|upload',
  `client_typed_name`     VARCHAR(150) DEFAULT NULL COMMENT 'only set when signature_type = type',
  `consent_accepted`   TINYINT(1)   NOT NULL DEFAULT 0,
  `client_signed_at`   DATETIME     DEFAULT NULL,
  `client_signed_ip`   VARCHAR(45)  DEFAULT NULL,
  `client_signed_device` VARCHAR(255) DEFAULT NULL COMMENT 'user agent string, captured at signing',
  `declined_at`        DATETIME     DEFAULT NULL,
  `decline_reason`     VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_application_id` (`application_id`),
  KEY `idx_prospect_id` (`prospect_id`),
  UNIQUE KEY `uniq_active_application` (`active_application_id`),
  UNIQUE KEY `uniq_sign_token` (`sign_token`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- Run these ALTERs if upgrading an existing table created before the unique-active-application guard:
-- ALTER TABLE `tbl_agreement_agreement`
--   ADD COLUMN `active_application_id` INT(11) GENERATED ALWAYS AS (IF(`hide` = 0, `application_id`, NULL)) VIRTUAL AFTER `update_on`,
--   ADD UNIQUE KEY `uniq_active_application` (`active_application_id`);

-- Run these ALTERs if upgrading an existing table created before the Create/Edit Agreement form fields:
-- ALTER TABLE `tbl_agreement_agreement`
--   ADD COLUMN `reference_number` VARCHAR(30) DEFAULT NULL AFTER `update_on`,
--   ADD COLUMN `agreement_date` DATE DEFAULT NULL,
--   ADD COLUMN `consultant_name` VARCHAR(150) DEFAULT NULL,
--   ADD COLUMN `rcic_number` VARCHAR(30) DEFAULT NULL,
--   ADD COLUMN `currency` VARCHAR(10) DEFAULT 'CAD',
--   ADD COLUMN `template_name` VARCHAR(100) DEFAULT 'Default Template',
--   ADD COLUMN `service_fee` DECIMAL(10,2) DEFAULT 0,
--   ADD COLUMN `gst_rate` DECIMAL(5,2) DEFAULT 5.00,
--   ADD COLUMN `gst_amount` DECIMAL(10,2) DEFAULT 0,
--   ADD COLUMN `government_fee` DECIMAL(10,2) DEFAULT 0,
--   ADD COLUMN `other_fee` DECIMAL(10,2) DEFAULT 0,
--   ADD COLUMN `total_amount` DECIMAL(10,2) DEFAULT 0,
--   ADD COLUMN `require_client_signature` TINYINT(1) DEFAULT 1,
--   ADD COLUMN `require_consultant_signature` TINYINT(1) DEFAULT 1,
--   ADD COLUMN `email_verification` TINYINT(1) DEFAULT 1,
--   ADD COLUMN `send_reminder` TINYINT(1) DEFAULT 1,
--   ADD COLUMN `reminder_days` INT(11) DEFAULT 3,
--   ADD COLUMN `max_reminders` INT(11) DEFAULT 2;

-- Run these ALTERs if upgrading an existing table created before the client signing page:
-- ALTER TABLE `tbl_agreement_agreement`
--   ADD COLUMN `sign_token` VARCHAR(64) DEFAULT NULL AFTER `max_reminders`,
--   ADD COLUMN `viewed_at` DATETIME DEFAULT NULL,
--   ADD COLUMN `viewed_ip` VARCHAR(45) DEFAULT NULL,
--   ADD COLUMN `consultant_signature` VARCHAR(255) DEFAULT NULL,
--   ADD COLUMN `client_signature` VARCHAR(255) DEFAULT NULL,
--   ADD COLUMN `client_signature_type` VARCHAR(10) DEFAULT NULL,
--   ADD COLUMN `client_typed_name` VARCHAR(150) DEFAULT NULL,
--   ADD COLUMN `consent_accepted` TINYINT(1) NOT NULL DEFAULT 0,
--   ADD COLUMN `client_signed_at` DATETIME DEFAULT NULL,
--   ADD COLUMN `client_signed_ip` VARCHAR(45) DEFAULT NULL,
--   ADD COLUMN `client_signed_device` VARCHAR(255) DEFAULT NULL,
--   ADD COLUMN `declined_at` DATETIME DEFAULT NULL,
--   ADD COLUMN `decline_reason` VARCHAR(255) DEFAULT NULL,
--   ADD UNIQUE KEY `uniq_sign_token` (`sign_token`);
